# Generated by Django 3.1.7 on 2021-03-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210326_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='email',
            new_name='username',
        ),
    ]
