# Generated by Django 3.1.7 on 2021-03-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loggedinuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subject_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
        ),
    ]
