# Generated by Django 3.1.7 on 2021-03-27 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210326_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionpack'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
