# Generated by Django 3.1.7 on 2021-03-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210328_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionpack'),
        ),
    ]
