# Generated by Django 3.1.7 on 2021-05-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210514_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='role',
            field=models.CharField(default='student', max_length=100),
            preserve_default=False,
        ),
    ]
