# Generated by Django 3.1.7 on 2021-09-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewQuestion',
        ),
    ]
