# Generated by Django 3.1.7 on 2021-09-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ststus',
            new_name='status',
        ),
    ]
